apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-java
  template:
    metadata:
      labels:
        app: kubernetes-java
    spec:
      containers:
        - name: kubernetes-java
          image: suneel00/kubernetes:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-java-service
spec:
  type: NodePort
  selector:
    app: kubernetes-java
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30163
