name: Java CI/CD to Kubernetes

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: suneel00/kubernetes
  REGISTRY: docker.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Log in to Docker Hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: echo "$DOCKER_PASSWORD" | docker login -u suneel00 --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME:${{ github.run_number }} .
        docker push $IMAGE_NAME:${{ github.run_number }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      env:
        KUBECONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        mkdir -p ~/.kube
        echo "$KUBECONFIG_DATA" | base64 -d > ~/.kube/config

    - name: Update image in manifest
      run: sed -i "s|image: .*|image: ${IMAGE_NAME}:${{ github.run_number }}|" k8s/deploymentservice.yaml

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/deploymentservice.yaml
